@baseUrl = http://localhost:3000

### Buscar todos os usuários
GET {{baseUrl}}/users?limit=100&offset=0

### Buscar um usuário específico
GET {{baseUrl}}/users/e110575c-db2c-42d3-b3fb-f5fe5ff587f8

### Criar um novo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "anderson",
  "email": "anderson@example.com",
  "password": "securepassword"
}

### Atualizar um novo usuário
PATCH {{baseUrl}}/users/e110575c-db2c-42d3-b3fb-f5fe5ff587f8
Content-Type: application/json

{
  "name": "Anderson",
  "email": "anderson@example1.com",
  "password": "securepassword"
}


### Deletar um usuário
DELETE {{baseUrl}}/users/fd4b742f-0f7d-4fe9-b3c2-41c35c9e8606


### Restaurar um usuário deletado
POST {{baseUrl}}/users/fd4b742f-0f7d-4fe9-b3c2-41c35c9e8606/restore
